New plugin to check warnings on posts and script to migrate posts
facundobatista/blog pull request #32
Opened 2017-12-05 05:08 UTC by marian-vignau

#30

2017-12-08 19:21 UTC, facundobatista requested changes
Genial idea la de este script... ahí hice algunos comentarios específicos en el código...

Muchas gracias!!!

2017-12-08 19:21 UTC, facundobatista commented on migrate.py
> +
Falta el docstring acá...

2017-12-08 19:21 UTC, facundobatista commented on migrate.py
> +    """Loop through all post in 'done' folder """
Falta el punto al final del docstring

2017-12-08 19:21 UTC, facundobatista commented on migrate.py
> +]
No me gusta este "replacements". 

Sí, hay cosas para corregir, pero cómo sabés si son todas? Incluso siendo todas las actuales, en el futuro van a aparecer más... 

Entonces, me encantaría alguna manera de "encontrar" cuales están mal y corregirlas, pero no sé si se puede hacer automáticamente... vos cómo encontraste estas que pusiste acá?

2017-12-08 19:21 UTC, facundobatista commented on migrate.py
> +def progress():
no lo hagas a mano, mirá la lib "progress" en PyPI...

2017-12-08 19:21 UTC, facundobatista commented on migrate.py
> +        if file_in.endswith("txt"):
acá estaría bueno un "else: print(tenemso un archivo raro)", como para asegurarnos que o lo procesamos o nos damos cuenta, y no nos estamos perdiendo nada sólo por que está mal nombrado

2017-12-08 19:21 UTC, facundobatista commented on migrate.py
> +                file_out = os.path.join(path_dest, file_in.split(".", -1)[0] + ".rst")
ese "split" que hacés se rompe si el archivo llega a tener un punto como parte del nombre... quizás no sea el caso en estos archivos, pero mejor hacerlo genérico y te sirve para otros lados... lo que tenés que hacer es: file_in.rsplit(".", 1)[0]

2017-12-08 19:21 UTC, facundobatista commented on migrate.py
> +                if not os.path.exists(file_out):
y si el archivo existe, qué hacemos? por qué no sobreescribirlo? al menos tirar un warning?

2017-12-08 19:21 UTC, facundobatista commented on migrate.py
> +                    with open(file_out, "wt+", encoding="utf8") as fout:
por qué el "+" en el modo?

2017-12-08 19:21 UTC, facundobatista commented on migrate.py
> +            with open(os.path.join(path_source, file_in), "rt+", encoding="utf8") as fin:
por qué el "+" en el modo?

2017-12-10 16:44 UTC, marian-vignau commented on migrate.py
> +                    with open(file_out, "wt+", encoding="utf8") as fout:
no debe estar

2017-12-10 16:45 UTC, marian-vignau commented on migrate.py
> +def progress():
Saqué.
No sirve si además pongo warnings intercalados
Ahora agrego un totalizador al final.

2017-12-10 16:45 UTC, marian-vignau commented on migrate.py
> +            with open(os.path.join(path_source, file_in), "rt+", encoding="utf8") as fin:
Sacado

2017-12-10 16:46 UTC, marian-vignau commented on migrate.py
> +]
Entonces no se autocorrige

2017-12-10 18:53 UTC, facundobatista requested changes
Un comentario menor sobre un docstring, y otro para que mejores la interfaz contra una función (si tenés dudas con respecto a esto último, avisame)

Por otro lado, hay problemas con los archivos:

- qué son estos no-extension y other-extension.csv que aparecen acá??

- borraste todos los .rst que ya teníamos

En general, acordate de esto: luego de commitear, y antes de decir "ya está listo para review", siempre hacé un `git diff master`, y ahí vas a ver todos los cambios que estás proponiendo (y si hay algo que sobre/falte, lo arreglás).

Gracias!

2017-12-10 18:53 UTC, facundobatista commented on migrate.py
> +    Return file_out name or error message."""
La primera linea del docstring está bien. Para la segunda, tenés que dejar una linea en blanco. Y luego terminar con el """ de cierre en una linea separada. 

Detalles en  https://www.python.org/dev/peps/pep-0257/

2017-12-10 18:53 UTC, facundobatista commented on migrate.py
> +        error, output = check_file(filename)
check_file debería devolver el nombre de salida si todo está bien, y generar un error si hay algún problema, entonces acá vos hacés un try/except alrededor de la llamada, y listo! el mensaje a mostrar lo tomás de la excepción y ya

Por otro lado, "output" no es buen nombre para "el nombre de archivo destino"

2017-12-12 15:10 UTC, facundobatista requested changes
A couple of small changes

2017-12-12 15:10 UTC, facundobatista commented on migrate.py
> +            total[True] += 1
process_file y la suma en total no deberían generar una excepción, así que no los metas en el "try"

2017-12-12 15:10 UTC, facundobatista commented on migrate.py
> +        raise Exception("File '{}' doesn't have file extension and won't be processed.".format(filename))
No uses "Exception", es demasiado genérica... en los primeros dos van bien ValueError... en el tercero no aplica tanto, pero si usás ValueError en todo queda más simple... Obvio también cambiá el "except" arriba

2017-12-13 17:51 UTC, facundobatista commented
Wonderful, thank you very much!!

2017-12-13 17:51 UTC, merged